// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToteSync.DAL;

#nullable disable

namespace ToteSync.DAL.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240622165207_ItemEntityDataSeeding")]
    partial class ItemEntityDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToteSync.Domain.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category_description");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("category_name");

                    b.Property<int>("CategoryUserId")
                        .HasColumnType("integer")
                        .HasColumnName("category_user_id");

                    b.HasKey("CategoryId")
                        .HasName("categories_pk");

                    b.HasIndex("CategoryUserId");

                    b.ToTable("categories", "tote");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Verduras",
                            CategoryUserId = 1
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Frutas",
                            CategoryUserId = 1
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Carnes",
                            CategoryUserId = 1
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Lácteos",
                            CategoryUserId = 1
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Granos",
                            CategoryUserId = 1
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Bebidas",
                            CategoryUserId = 2
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Panadería",
                            CategoryUserId = 2
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Pescados",
                            CategoryUserId = 2
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Aceites",
                            CategoryUserId = 2
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Snacks",
                            CategoryUserId = 2
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Condimentos",
                            CategoryUserId = 3
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Cereales",
                            CategoryUserId = 3
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Dulces",
                            CategoryUserId = 3
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Helados",
                            CategoryUserId = 3
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Pastas",
                            CategoryUserId = 3
                        },
                        new
                        {
                            CategoryId = 16,
                            CategoryName = "Legumbres",
                            CategoryUserId = 4
                        },
                        new
                        {
                            CategoryId = 17,
                            CategoryName = "Especias",
                            CategoryUserId = 4
                        },
                        new
                        {
                            CategoryId = 18,
                            CategoryName = "Bebidas alcohólicas",
                            CategoryUserId = 4
                        },
                        new
                        {
                            CategoryId = 19,
                            CategoryName = "Conservas",
                            CategoryUserId = 4
                        },
                        new
                        {
                            CategoryId = 20,
                            CategoryName = "Salsas",
                            CategoryUserId = 4
                        });
                });

            modelBuilder.Entity("ToteSync.Domain.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime>("GroupCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("group_created_date")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("GroupModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("group_modified_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("group_name");

                    b.HasKey("GroupId")
                        .HasName("groups_pk");

                    b.ToTable("groups", "tote");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            GroupCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Familia Fonseca Moncada"
                        },
                        new
                        {
                            GroupId = 2,
                            GroupCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Familia Fonseca Mata"
                        },
                        new
                        {
                            GroupId = 3,
                            GroupCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Familia Quintana Perez"
                        });
                });

            modelBuilder.Entity("ToteSync.Domain.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("group_member_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupMemberId"));

                    b.Property<int>("GroupMemberGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_member_group_id");

                    b.Property<int>("GroupMemberUserId")
                        .HasColumnType("integer")
                        .HasColumnName("group_member_user_id");

                    b.HasKey("GroupMemberId")
                        .HasName("group_members_pk");

                    b.HasIndex("GroupMemberGroupId");

                    b.HasIndex(new[] { "GroupMemberUserId", "GroupMemberGroupId" }, "group_members_user_group_uindex")
                        .IsUnique();

                    b.ToTable("group_members", "tote");

                    b.HasData(
                        new
                        {
                            GroupMemberId = 1,
                            GroupMemberGroupId = 1,
                            GroupMemberUserId = 1
                        },
                        new
                        {
                            GroupMemberId = 2,
                            GroupMemberGroupId = 1,
                            GroupMemberUserId = 4
                        },
                        new
                        {
                            GroupMemberId = 3,
                            GroupMemberGroupId = 2,
                            GroupMemberUserId = 1
                        },
                        new
                        {
                            GroupMemberId = 4,
                            GroupMemberGroupId = 2,
                            GroupMemberUserId = 2
                        },
                        new
                        {
                            GroupMemberId = 5,
                            GroupMemberGroupId = 3,
                            GroupMemberUserId = 2
                        },
                        new
                        {
                            GroupMemberId = 6,
                            GroupMemberGroupId = 3,
                            GroupMemberUserId = 3
                        });
                });

            modelBuilder.Entity("ToteSync.Domain.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("ItemCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("item_category_id");

                    b.Property<DateTime>("ItemCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("item_created_date")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ItemModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("item_modified_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("item_name");

                    b.Property<int>("ItemUserId")
                        .HasColumnType("integer")
                        .HasColumnName("item_user_id");

                    b.HasKey("ItemId")
                        .HasName("items_pk");

                    b.HasIndex(new[] { "ItemCategoryId", "ItemUserId", "ItemName" }, "items_category_user_name_uindex")
                        .IsUnique()
                        .HasFilter("(item_category_id IS NOT NULL)");

                    b.HasIndex(new[] { "ItemUserId", "ItemName" }, "items_user_name_uindex")
                        .IsUnique()
                        .HasFilter("(item_category_id IS NULL)");

                    b.ToTable("items", "tote");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            ItemCategoryId = 1,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Zanahoria",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 2,
                            ItemCategoryId = 1,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Tomate",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 3,
                            ItemCategoryId = 1,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Lechuga",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 4,
                            ItemCategoryId = 1,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Pepino",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 5,
                            ItemCategoryId = 1,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Espinaca",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 6,
                            ItemCategoryId = 2,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Manzana",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 7,
                            ItemCategoryId = 2,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Plátano",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 8,
                            ItemCategoryId = 2,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Uva",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 9,
                            ItemCategoryId = 2,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Naranja",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 10,
                            ItemCategoryId = 2,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Pera",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 11,
                            ItemCategoryId = 3,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Pollo",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 12,
                            ItemCategoryId = 3,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Res",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 13,
                            ItemCategoryId = 3,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Cerdo",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 14,
                            ItemCategoryId = 3,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Pavo",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 15,
                            ItemCategoryId = 3,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Cordero",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 16,
                            ItemCategoryId = 4,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Queso",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 17,
                            ItemCategoryId = 4,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Leche",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 18,
                            ItemCategoryId = 4,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Yogur",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 19,
                            ItemCategoryId = 4,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Mantequilla",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 20,
                            ItemCategoryId = 4,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Crema",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 21,
                            ItemCategoryId = 5,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Arroz",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 22,
                            ItemCategoryId = 5,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Frijoles",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 23,
                            ItemCategoryId = 5,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Maíz",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 24,
                            ItemCategoryId = 5,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Lentejas",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 25,
                            ItemCategoryId = 5,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Avena",
                            ItemUserId = 1
                        },
                        new
                        {
                            ItemId = 26,
                            ItemCategoryId = 6,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Agua",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 27,
                            ItemCategoryId = 6,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Jugo",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 28,
                            ItemCategoryId = 6,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Refresco",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 29,
                            ItemCategoryId = 6,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Té",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 30,
                            ItemCategoryId = 6,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Café",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 31,
                            ItemCategoryId = 7,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Pan integral",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 32,
                            ItemCategoryId = 7,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Pan blanco",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 33,
                            ItemCategoryId = 7,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Pan de centeno",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 34,
                            ItemCategoryId = 7,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Pan de avena",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 35,
                            ItemCategoryId = 7,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Baguette",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 36,
                            ItemCategoryId = 8,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Salmón",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 37,
                            ItemCategoryId = 8,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Atún",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 38,
                            ItemCategoryId = 8,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Trucha",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 39,
                            ItemCategoryId = 8,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Bacalao",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 40,
                            ItemCategoryId = 8,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Tilapia",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 41,
                            ItemCategoryId = 9,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Aceite de oliva",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 42,
                            ItemCategoryId = 9,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Aceite de girasol",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 43,
                            ItemCategoryId = 9,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Aceite de coco",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 44,
                            ItemCategoryId = 9,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Aceite de aguacate",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 45,
                            ItemCategoryId = 9,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Aceite de sésamo",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 46,
                            ItemCategoryId = 10,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Papas fritas",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 47,
                            ItemCategoryId = 10,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Galletas",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 48,
                            ItemCategoryId = 10,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Palomitas",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 49,
                            ItemCategoryId = 10,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Chocolates",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 50,
                            ItemCategoryId = 10,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Nueces",
                            ItemUserId = 2
                        },
                        new
                        {
                            ItemId = 51,
                            ItemCategoryId = 11,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Sal",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 52,
                            ItemCategoryId = 11,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Pimienta",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 53,
                            ItemCategoryId = 11,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Orégano",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 54,
                            ItemCategoryId = 11,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Comino",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 55,
                            ItemCategoryId = 11,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Canela",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 56,
                            ItemCategoryId = 12,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Avena",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 57,
                            ItemCategoryId = 12,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Trigo",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 58,
                            ItemCategoryId = 12,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Maíz",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 59,
                            ItemCategoryId = 12,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Cebada",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 60,
                            ItemCategoryId = 12,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Quinoa",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 61,
                            ItemCategoryId = 13,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Chocolate",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 62,
                            ItemCategoryId = 13,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Caramelo",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 63,
                            ItemCategoryId = 13,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Chicle",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 64,
                            ItemCategoryId = 13,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Gomitas",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 65,
                            ItemCategoryId = 13,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Barras de cereal",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 66,
                            ItemCategoryId = 14,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Helado de vainilla",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 67,
                            ItemCategoryId = 14,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Helado de chocolate",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 68,
                            ItemCategoryId = 14,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Helado de fresa",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 69,
                            ItemCategoryId = 14,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Helado de menta",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 70,
                            ItemCategoryId = 14,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Helado de coco",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 71,
                            ItemCategoryId = 15,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Espagueti",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 72,
                            ItemCategoryId = 15,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Fideos",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 73,
                            ItemCategoryId = 15,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Lasaña",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 74,
                            ItemCategoryId = 15,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Raviolis",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 75,
                            ItemCategoryId = 15,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Macarrones",
                            ItemUserId = 3
                        },
                        new
                        {
                            ItemId = 76,
                            ItemCategoryId = 16,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Lentejas",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 77,
                            ItemCategoryId = 16,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Garbanzos",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 78,
                            ItemCategoryId = 16,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Frijoles",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 79,
                            ItemCategoryId = 16,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Habas",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 80,
                            ItemCategoryId = 16,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Chícharos",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 81,
                            ItemCategoryId = 17,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Pimienta negra",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 82,
                            ItemCategoryId = 17,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Pimienta blanca",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 83,
                            ItemCategoryId = 17,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Curry",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 84,
                            ItemCategoryId = 17,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Paprika",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 85,
                            ItemCategoryId = 17,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Clavo",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 86,
                            ItemCategoryId = 18,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Cerveza",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 87,
                            ItemCategoryId = 18,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Vino tinto",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 88,
                            ItemCategoryId = 18,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Vino blanco",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 89,
                            ItemCategoryId = 18,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Ron",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 90,
                            ItemCategoryId = 18,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Vodka",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 91,
                            ItemCategoryId = 19,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Atún enlatado",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 92,
                            ItemCategoryId = 19,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Maíz enlatado",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 93,
                            ItemCategoryId = 19,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Guisantes enlatados",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 94,
                            ItemCategoryId = 19,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Tomate enlatado",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 95,
                            ItemCategoryId = 19,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Champiñones enlatados",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 96,
                            ItemCategoryId = 20,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Salsa de tomate",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 97,
                            ItemCategoryId = 20,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Salsa BBQ",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 98,
                            ItemCategoryId = 20,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Salsa Alfredo",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 99,
                            ItemCategoryId = 20,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Salsa de soya",
                            ItemUserId = 4
                        },
                        new
                        {
                            ItemId = 100,
                            ItemCategoryId = 20,
                            ItemCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemModifiedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemName = "Salsa de ajo",
                            ItemUserId = 4
                        });
                });

            modelBuilder.Entity("ToteSync.Domain.ShoppingList", b =>
                {
                    b.Property<int>("ShoppingListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShoppingListId"));

                    b.Property<DateTime>("ShoppingListCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shopping_list_created_date")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ShoppingListGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_group_id");

                    b.Property<DateTime>("ShoppingListModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shopping_list_modified_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ShoppingListName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shopping_list_name");

                    b.Property<int>("ShoppingListUserId")
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_user_id");

                    b.HasKey("ShoppingListId")
                        .HasName("shopping_lists_pk");

                    b.HasIndex("ShoppingListUserId");

                    b.HasIndex(new[] { "ShoppingListGroupId", "ShoppingListName", "ShoppingListUserId" }, "shopping_lists_group_name_user_uindex")
                        .IsUnique();

                    b.ToTable("shopping_lists", "tote");
                });

            modelBuilder.Entity("ToteSync.Domain.ShoppingListItem", b =>
                {
                    b.Property<int>("ShoppingListItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShoppingListItemId"));

                    b.Property<int>("ShoppingListItemItemId")
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_item_item_id");

                    b.Property<string>("ShoppingListItemNotes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("shopping_list_item_notes");

                    b.Property<int>("ShoppingListItemQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("shopping_list_item_quantity");

                    b.Property<int>("ShoppingListItemShoppingListId")
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_item_shopping_list_id");

                    b.HasKey("ShoppingListItemId")
                        .HasName("shopping_list_items_pk");

                    b.HasIndex("ShoppingListItemShoppingListId");

                    b.HasIndex(new[] { "ShoppingListItemItemId", "ShoppingListItemShoppingListId" }, "shopping_list_items_item_list_uindex")
                        .IsUnique();

                    b.ToTable("shopping_list_items", "tote");
                });

            modelBuilder.Entity("ToteSync.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserAvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_avatar_url");

                    b.Property<DateOnly>("UserBirthdate")
                        .HasColumnType("date")
                        .HasColumnName("user_birthdate");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserFirstLastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_first_last_name");

                    b.Property<bool>("UserIsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("user_is_active");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_phone_number");

                    b.Property<string>("UserSecondLastName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_second_last_name");

                    b.Property<int>("UserZipCode")
                        .HasColumnType("integer")
                        .HasColumnName("user_zip_code");

                    b.HasKey("UserId")
                        .HasName("users_pk");

                    b.HasIndex(new[] { "UserEmail" }, "users_user_email_uindex")
                        .IsUnique();

                    b.HasIndex(new[] { "UserPhoneNumber" }, "users_user_phone_number_uindex")
                        .IsUnique();

                    b.ToTable("users", "tote");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            UserAvatarUrl = "https://www.google.com/",
                            UserBirthdate = new DateOnly(2001, 5, 14),
                            UserEmail = "pablo.fonsecam@outlook.com",
                            UserFirstLastName = "Fonseca",
                            UserIsActive = true,
                            UserName = "Pablo",
                            UserPhoneNumber = "87719888",
                            UserSecondLastName = "Moncada",
                            UserZipCode = 506
                        },
                        new
                        {
                            UserId = 2,
                            UserAvatarUrl = "https://www.fakephoto.com/",
                            UserBirthdate = new DateOnly(2003, 6, 3),
                            UserEmail = "perezvirginia889@gmail.com",
                            UserFirstLastName = "Mata",
                            UserIsActive = true,
                            UserName = "Virginia",
                            UserPhoneNumber = "72892168",
                            UserSecondLastName = "Perez",
                            UserZipCode = 506
                        },
                        new
                        {
                            UserId = 3,
                            UserAvatarUrl = "https://www.fakecatphoto.com/",
                            UserBirthdate = new DateOnly(1989, 5, 30),
                            UserEmail = "daniel.bleach1@gmail.com",
                            UserFirstLastName = "Quintana",
                            UserIsActive = true,
                            UserName = "Daniel",
                            UserPhoneNumber = "70068596",
                            UserSecondLastName = "Medina",
                            UserZipCode = 506
                        },
                        new
                        {
                            UserId = 4,
                            UserAvatarUrl = "https://www.fakephoto.com/",
                            UserBirthdate = new DateOnly(1973, 10, 23),
                            UserEmail = "dafotr@outlook.com",
                            UserFirstLastName = "Fonseca",
                            UserIsActive = true,
                            UserName = "Danny",
                            UserPhoneNumber = "83030630",
                            UserSecondLastName = "Trejos",
                            UserZipCode = 506
                        });
                });

            modelBuilder.Entity("ToteSync.Domain.Category", b =>
                {
                    b.HasOne("ToteSync.Domain.User", "CategoryUser")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("categories_users_user_id_fk");

                    b.Navigation("CategoryUser");
                });

            modelBuilder.Entity("ToteSync.Domain.GroupMember", b =>
                {
                    b.HasOne("ToteSync.Domain.Group", "GroupMemberGroup")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupMemberGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("group_members_groups_fk");

                    b.HasOne("ToteSync.Domain.User", "GroupMemberUser")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupMemberUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("group_members_users_fk");

                    b.Navigation("GroupMemberGroup");

                    b.Navigation("GroupMemberUser");
                });

            modelBuilder.Entity("ToteSync.Domain.Item", b =>
                {
                    b.HasOne("ToteSync.Domain.Category", "ItemCategory")
                        .WithMany("Items")
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("items_categories_fk");

                    b.HasOne("ToteSync.Domain.User", "ItemUser")
                        .WithMany("Items")
                        .HasForeignKey("ItemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("items_users_fk");

                    b.Navigation("ItemCategory");

                    b.Navigation("ItemUser");
                });

            modelBuilder.Entity("ToteSync.Domain.ShoppingList", b =>
                {
                    b.HasOne("ToteSync.Domain.Group", "ShoppingListGroup")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("ShoppingListGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("shopping_lists_groups_fk");

                    b.HasOne("ToteSync.Domain.User", "ShoppingListUser")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("ShoppingListUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shopping_lists_users_fk");

                    b.Navigation("ShoppingListGroup");

                    b.Navigation("ShoppingListUser");
                });

            modelBuilder.Entity("ToteSync.Domain.ShoppingListItem", b =>
                {
                    b.HasOne("ToteSync.Domain.Item", "ShoppingListItemItem")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("ShoppingListItemItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("shopping_list_items_items_fk");

                    b.HasOne("ToteSync.Domain.ShoppingList", "ShoppingListItemShoppingList")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("ShoppingListItemShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shopping_list_items_shopping_lists_fk");

                    b.Navigation("ShoppingListItemItem");

                    b.Navigation("ShoppingListItemShoppingList");
                });

            modelBuilder.Entity("ToteSync.Domain.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ToteSync.Domain.Group", b =>
                {
                    b.Navigation("GroupMembers");

                    b.Navigation("ShoppingLists");
                });

            modelBuilder.Entity("ToteSync.Domain.Item", b =>
                {
                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("ToteSync.Domain.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("ToteSync.Domain.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("GroupMembers");

                    b.Navigation("Items");

                    b.Navigation("ShoppingLists");
                });
#pragma warning restore 612, 618
        }
    }
}
