// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ToteSync.DAL;

#nullable disable

namespace ToteSync.DAL.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240622155343_FirstStepsOnDataSeeding")]
    partial class FirstStepsOnDataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ToteSync.Domain.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category_description");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("category_name");

                    b.Property<int>("CategoryUserId")
                        .HasColumnType("integer")
                        .HasColumnName("category_user_id");

                    b.HasKey("CategoryId")
                        .HasName("categories_pk");

                    b.HasIndex("CategoryUserId");

                    b.ToTable("categories", "tote");
                });

            modelBuilder.Entity("ToteSync.Domain.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime>("GroupCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("group_created_date")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("GroupModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("group_modified_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("group_name");

                    b.HasKey("GroupId")
                        .HasName("groups_pk");

                    b.ToTable("groups", "tote");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            GroupCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Familia Fonseca Moncada"
                        },
                        new
                        {
                            GroupId = 2,
                            GroupCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Familia Fonseca Mata"
                        },
                        new
                        {
                            GroupId = 3,
                            GroupCreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            GroupName = "Familia Quintana Perez"
                        });
                });

            modelBuilder.Entity("ToteSync.Domain.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("group_member_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupMemberId"));

                    b.Property<int>("GroupMemberGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_member_group_id");

                    b.Property<int>("GroupMemberUserId")
                        .HasColumnType("integer")
                        .HasColumnName("group_member_user_id");

                    b.HasKey("GroupMemberId")
                        .HasName("group_members_pk");

                    b.HasIndex("GroupMemberGroupId");

                    b.HasIndex(new[] { "GroupMemberUserId", "GroupMemberGroupId" }, "group_members_user_group_uindex")
                        .IsUnique();

                    b.ToTable("group_members", "tote");

                    b.HasData(
                        new
                        {
                            GroupMemberId = 1,
                            GroupMemberGroupId = 1,
                            GroupMemberUserId = 1
                        },
                        new
                        {
                            GroupMemberId = 2,
                            GroupMemberGroupId = 1,
                            GroupMemberUserId = 4
                        },
                        new
                        {
                            GroupMemberId = 3,
                            GroupMemberGroupId = 2,
                            GroupMemberUserId = 1
                        },
                        new
                        {
                            GroupMemberId = 4,
                            GroupMemberGroupId = 2,
                            GroupMemberUserId = 2
                        },
                        new
                        {
                            GroupMemberId = 5,
                            GroupMemberGroupId = 3,
                            GroupMemberUserId = 2
                        },
                        new
                        {
                            GroupMemberId = 6,
                            GroupMemberGroupId = 3,
                            GroupMemberUserId = 3
                        });
                });

            modelBuilder.Entity("ToteSync.Domain.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<int?>("ItemCategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("item_category_id");

                    b.Property<DateTime>("ItemCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("item_created_date")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ItemModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("item_modified_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("item_name");

                    b.Property<int>("ItemUserId")
                        .HasColumnType("integer")
                        .HasColumnName("item_user_id");

                    b.HasKey("ItemId")
                        .HasName("items_pk");

                    b.HasIndex(new[] { "ItemCategoryId", "ItemUserId", "ItemName" }, "items_category_user_name_uindex")
                        .IsUnique()
                        .HasFilter("(item_category_id IS NOT NULL)");

                    b.HasIndex(new[] { "ItemUserId", "ItemName" }, "items_user_name_uindex")
                        .IsUnique()
                        .HasFilter("(item_category_id IS NULL)");

                    b.ToTable("items", "tote");
                });

            modelBuilder.Entity("ToteSync.Domain.ShoppingList", b =>
                {
                    b.Property<int>("ShoppingListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShoppingListId"));

                    b.Property<DateTime>("ShoppingListCreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shopping_list_created_date")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ShoppingListGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_group_id");

                    b.Property<DateTime>("ShoppingListModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("shopping_list_modified_date")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ShoppingListName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("shopping_list_name");

                    b.Property<int>("ShoppingListUserId")
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_user_id");

                    b.HasKey("ShoppingListId")
                        .HasName("shopping_lists_pk");

                    b.HasIndex("ShoppingListUserId");

                    b.HasIndex(new[] { "ShoppingListGroupId", "ShoppingListName", "ShoppingListUserId" }, "shopping_lists_group_name_user_uindex")
                        .IsUnique();

                    b.ToTable("shopping_lists", "tote");
                });

            modelBuilder.Entity("ToteSync.Domain.ShoppingListItem", b =>
                {
                    b.Property<int>("ShoppingListItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_item_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShoppingListItemId"));

                    b.Property<int>("ShoppingListItemItemId")
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_item_item_id");

                    b.Property<string>("ShoppingListItemNotes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("shopping_list_item_notes");

                    b.Property<int>("ShoppingListItemQuantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("shopping_list_item_quantity");

                    b.Property<int>("ShoppingListItemShoppingListId")
                        .HasColumnType("integer")
                        .HasColumnName("shopping_list_item_shopping_list_id");

                    b.HasKey("ShoppingListItemId")
                        .HasName("shopping_list_items_pk");

                    b.HasIndex("ShoppingListItemShoppingListId");

                    b.HasIndex(new[] { "ShoppingListItemItemId", "ShoppingListItemShoppingListId" }, "shopping_list_items_item_list_uindex")
                        .IsUnique();

                    b.ToTable("shopping_list_items", "tote");
                });

            modelBuilder.Entity("ToteSync.Domain.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserAvatarUrl")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_avatar_url");

                    b.Property<DateOnly>("UserBirthdate")
                        .HasColumnType("date")
                        .HasColumnName("user_birthdate");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserFirstLastName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_first_last_name");

                    b.Property<bool>("UserIsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("user_is_active");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("user_phone_number");

                    b.Property<string>("UserSecondLastName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("user_second_last_name");

                    b.Property<int>("UserZipCode")
                        .HasColumnType("integer")
                        .HasColumnName("user_zip_code");

                    b.HasKey("UserId")
                        .HasName("users_pk");

                    b.HasIndex(new[] { "UserEmail" }, "users_user_email_uindex")
                        .IsUnique();

                    b.HasIndex(new[] { "UserPhoneNumber" }, "users_user_phone_number_uindex")
                        .IsUnique();

                    b.ToTable("users", "tote");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            UserAvatarUrl = "https://www.google.com/",
                            UserBirthdate = new DateOnly(2001, 5, 14),
                            UserEmail = "pablo.fonsecam@outlook.com",
                            UserFirstLastName = "Fonseca",
                            UserIsActive = true,
                            UserName = "Pablo",
                            UserPhoneNumber = "87719888",
                            UserSecondLastName = "Moncada",
                            UserZipCode = 506
                        },
                        new
                        {
                            UserId = 2,
                            UserAvatarUrl = "https://www.fakephoto.com/",
                            UserBirthdate = new DateOnly(2003, 6, 3),
                            UserEmail = "perezvirginia889@gmail.com",
                            UserFirstLastName = "Mata",
                            UserIsActive = true,
                            UserName = "Virginia",
                            UserPhoneNumber = "72892168",
                            UserSecondLastName = "Perez",
                            UserZipCode = 506
                        },
                        new
                        {
                            UserId = 3,
                            UserAvatarUrl = "https://www.fakecatphoto.com/",
                            UserBirthdate = new DateOnly(1989, 5, 30),
                            UserEmail = "daniel.bleach1@gmail.com",
                            UserFirstLastName = "Quintana",
                            UserIsActive = true,
                            UserName = "Daniel",
                            UserPhoneNumber = "70068596",
                            UserSecondLastName = "Medina",
                            UserZipCode = 506
                        },
                        new
                        {
                            UserId = 4,
                            UserAvatarUrl = "https://www.fakephoto.com/",
                            UserBirthdate = new DateOnly(1973, 10, 23),
                            UserEmail = "dafotr@outlook.com",
                            UserFirstLastName = "Fonseca",
                            UserIsActive = true,
                            UserName = "Danny",
                            UserPhoneNumber = "83030630",
                            UserSecondLastName = "Trejos",
                            UserZipCode = 506
                        });
                });

            modelBuilder.Entity("ToteSync.Domain.Category", b =>
                {
                    b.HasOne("ToteSync.Domain.User", "CategoryUser")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("categories_users_user_id_fk");

                    b.Navigation("CategoryUser");
                });

            modelBuilder.Entity("ToteSync.Domain.GroupMember", b =>
                {
                    b.HasOne("ToteSync.Domain.Group", "GroupMemberGroup")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupMemberGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("group_members_groups_fk");

                    b.HasOne("ToteSync.Domain.User", "GroupMemberUser")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupMemberUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("group_members_users_fk");

                    b.Navigation("GroupMemberGroup");

                    b.Navigation("GroupMemberUser");
                });

            modelBuilder.Entity("ToteSync.Domain.Item", b =>
                {
                    b.HasOne("ToteSync.Domain.Category", "ItemCategory")
                        .WithMany("Items")
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("items_categories_fk");

                    b.HasOne("ToteSync.Domain.User", "ItemUser")
                        .WithMany("Items")
                        .HasForeignKey("ItemUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("items_users_fk");

                    b.Navigation("ItemCategory");

                    b.Navigation("ItemUser");
                });

            modelBuilder.Entity("ToteSync.Domain.ShoppingList", b =>
                {
                    b.HasOne("ToteSync.Domain.Group", "ShoppingListGroup")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("ShoppingListGroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("shopping_lists_groups_fk");

                    b.HasOne("ToteSync.Domain.User", "ShoppingListUser")
                        .WithMany("ShoppingLists")
                        .HasForeignKey("ShoppingListUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shopping_lists_users_fk");

                    b.Navigation("ShoppingListGroup");

                    b.Navigation("ShoppingListUser");
                });

            modelBuilder.Entity("ToteSync.Domain.ShoppingListItem", b =>
                {
                    b.HasOne("ToteSync.Domain.Item", "ShoppingListItemItem")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("ShoppingListItemItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("shopping_list_items_items_fk");

                    b.HasOne("ToteSync.Domain.ShoppingList", "ShoppingListItemShoppingList")
                        .WithMany("ShoppingListItems")
                        .HasForeignKey("ShoppingListItemShoppingListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("shopping_list_items_shopping_lists_fk");

                    b.Navigation("ShoppingListItemItem");

                    b.Navigation("ShoppingListItemShoppingList");
                });

            modelBuilder.Entity("ToteSync.Domain.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ToteSync.Domain.Group", b =>
                {
                    b.Navigation("GroupMembers");

                    b.Navigation("ShoppingLists");
                });

            modelBuilder.Entity("ToteSync.Domain.Item", b =>
                {
                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("ToteSync.Domain.ShoppingList", b =>
                {
                    b.Navigation("ShoppingListItems");
                });

            modelBuilder.Entity("ToteSync.Domain.User", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("GroupMembers");

                    b.Navigation("Items");

                    b.Navigation("ShoppingLists");
                });
#pragma warning restore 612, 618
        }
    }
}
